#ifndef MATISSEDICTIONNARYLABELS_H
#define MATISSEDICTIONNARYLABELS_H

#include <QObject>
#include <QString>
#include <QMap>
#include <QtDebug>

/*
 * Header file generated by MatisseDictionnaryValidator tool on ${timestamp}
 * This header allows internationalization of the dictionary labels (parameters and groups)
 *
 * Use lupdate (Qt Linguist) to udapte MatisseTools translation files
 *
 * DO NOT EDIT THIS FILE !
 */

namespace matisse
{

class MatisseDictionnaryLabels : public QObject
{
	Q_OBJECT

public:
	
	QMap<QString, QString> _paramLabelKeys;
	QMap<QString, QString> _groupLabelKeys;

	void declareLabels()
	{
		qDebug() << "Declaring parameters and groups labels for internationalization...";
		
		${declare_labels}
	}
	
	QString getParamLabel(QString paramName) {
		if (!_paramLabelKeys.contains(paramName)) {
			qCritical() << QString("No label declared for parameter '%1'").arg(paramName);
			return paramName;
		}
		
		QString labelKey = _paramLabelKeys.value(paramName);
		QString translation = tr(labelKey.toLatin1());
		return translation;
	}
	
	QString getGroupLabel(QString groupName) {
		if (!_groupLabelKeys.contains(groupName)) {
			qDebug() << QString("No label declared for group '%1'").arg(groupName);
			return groupName;
		}
	
		QString labelKey = _groupLabelKeys.value(groupName);
		QString translation = tr(labelKey.toLatin1());
		return translation;
	}

};

}

#endif // MATISSEDICTIONNARYLABELS_H
