#ifndef MATISSEDICTIONNARYLABELS_H
#define MATISSEDICTIONNARYLABELS_H

#include <QObject>
#include <QString>

/*
 * Header file generated by MatisseDictionnaryValidator tool on 11/02/2016 17:25:00
 * This header allows internationalization of the dictionary labels (parameters and groups)
 *
 * Use lupdate (Qt Linguist) to udapte MatisseTools translation files
 *
 * DO NOT EDIT THIS FILE !
 */

namespace MatisseTools
{

class MatisseDictionnaryLabels : public QObject
{
	Q_OBJECT

private:

	void declareLabels()
	{

		/*
		 * STRUCTURE : algo_param
		 */

		/* GROUP : general_algo_params */
		QString param_sift_code = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Code a executer pour le sift");
		QString param_scale_factor = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Reduction de la taille de l'image");
		QString param_maxdist_centers = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Distance max de recherche");
		QString param_min_matches = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Nombre min de correspondances");
		QString param_max_matches = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Nombre max de correspondances");
		QString param_First_processed_image = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Index premiere image");
		QString param_Last_processed_image = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Index derniere image");
		QString param_step_im = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Saut inter-images");

		/* GROUP : overlap_filtering_params */
		QString group_overlap_filtering_params = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Parametres de filtrage");
		QString param_filter_overlap = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Flag de filtrage");
		QString param_max_overlap = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Overlap max entre 2 images");
		QString param_min_overlap = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Overlap min entre 2 images");

		/* GROUP : bundle_adjustment_params */
		QString group_bundle_adjustment_params = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Ajustement de bundle");
		QString param_MaxIter = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Max number of iteration in the optimization");
		QString param_max_Roll = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Maximum Roll");
		QString param_max_Pitch = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Maximum Pitch");
		QString param_ba_method = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Mosaicking method");
		QString param_cosmetic_stretch = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Color/Constrast Stretching");

		/* GROUP : blending_displaying_params */
		QString group_blending_displaying_params = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Fusion et affichage");
		QString param_expo_comp_method = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Exposure compensation method");
		QString param_seam_method = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Images seaming method");
		QString param_blending_method = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Blending method");
		QString param_no_plot = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "No plot (just progress bars)");
		QString param_WriteGeoTiff = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Write a GeoTiff file");
		QString param_block_drawing = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Blocks drawing (better for memory use)");
		QString param_block_width = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Mean block width");
		QString param_block_height = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Mean block height");

		/*
		 * STRUCTURE : vehic_param
		 */

		/* GROUP : vehicle_params */
		QString param_reproj_std = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Sift matching precision (in pixels)");
		QString param_X_std = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "UTM X precision (std dev in m)");
		QString param_Y_std = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "UTM Y precision (m)");
		QString param_alt_std = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Altitude precision (m)");
		QString param_Roll_std = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Roll precision (rad)");
		QString param_Pitch_std = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Pitch precision (rad)");
		QString param_Yaw_std = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Yaw precision (rad)");

		/*
		 * STRUCTURE : cam_param
		 */

		/* GROUP : advanced_camera_params */
		QString group_advanced_camera_params = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Parametres reglages camera");
		QString param_K = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Matrice de la camera");
		QString param_V_Pose_C = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Position de la camera / centre de nav");

		/*
		 * STRUCTURE : video_input_param
		 */

		/* GROUP : video_input_params */
		QString param_idCamera = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "N° Camera");
		QString param_intervalCapture = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Interval de capture (ms)");

		/*
		 * STRUCTURE : dim2_param
		 */

		/* GROUP : network_nav_input_params */
		QString param_udp_port = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Port Udp dim2");

		/*
		 * STRUCTURE : dataset_param
		 */

		/* GROUP : output_and_geo_params */
		QString param_dataset_dir = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Chemin du dataset");
		QString param_output_dir = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Chemin de sortie");
		QString param_output_filename = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Fichier de sortie");
		QString param_navFile = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Navigation file");
		QString param_utm_zone = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Zone UTM");
		QString param_utm_hemisphere = QT_TRANSLATE_NOOP("MatisseTools::MatisseParametersManager", "Hemisphere UTM");

	}

};

}

#endif // MATISSEDICTIONNARYLABELS_H
