%YAML:1.0
---
camera_name: Victor HD
full_sensor_width: 1920
full_sensor_height: 1080
K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1430., 0., 960., 0., 1430., 540., 0., 0., 1. ]
distortion_model: 1
distortion_coeff: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 0., 0., 0., 0., 0. ]
vehicle_to_camera_transform: !!opencv-matrix
   rows: 1
   cols: 6
   dt: d
   data: [ 0., 0., 0., 0., 0., 0. ]
